/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app/knowledge-base'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFilesIdContextRouteImport } from './routes/api/files.$id.context'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdContextRoute = ApiFilesIdContextRouteImport.update({
  id: '/$id/context',
  path: '/$id/context',
  getParentRoute: () => ApiFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/chat': typeof AppChatRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/files/$id/context': typeof ApiFilesIdContextRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/chat': typeof AppChatRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/files/$id/context': typeof ApiFilesIdContextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_landing/': typeof LandingIndexRoute
  '/api/files/$id/context': typeof ApiFilesIdContextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/knowledge-base'
    | '/api/chat'
    | '/api/files'
    | '/api/health'
    | '/api/files/$id/context'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/knowledge-base'
    | '/api/chat'
    | '/api/files'
    | '/api/health'
    | '/api/files/$id/context'
  id:
    | '__root__'
    | '/_app'
    | '/_landing'
    | '/_app/chat'
    | '/_app/knowledge-base'
    | '/api/chat'
    | '/api/files'
    | '/api/health'
    | '/_landing/'
    | '/api/files/$id/context'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id/context': {
      id: '/api/files/$id/context'
      path: '/$id/context'
      fullPath: '/api/files/$id/context'
      preLoaderRoute: typeof ApiFilesIdContextRouteImport
      parentRoute: typeof ApiFilesRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesIdContextRoute: typeof ApiFilesIdContextRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesIdContextRoute: ApiFilesIdContextRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
